"""Rendering of the pipeline progress table (text, ECSV, HTML)."""

import datetime
import html
import os


# `src` distinguishes rows the pipeline will act on from hand-built directories
# it only observes.  It is a column of its own rather than a note, so a stall
# reason can never mask the fact that a run is frozen.
COLUMNS = ["halo", "box", "stage", "src", "state", "last", "z", "cycle", "jobid", "note"]

_STATE_ORDER = ["DONE", "RUNNING", "QUEUED", "BUILDING", "READY", "BLOCKED", "STALLED"]


def _fmt(value, kind=None):
    if value is None:
        return "-"
    if kind == "z":
        return "%.3f" % value
    return str(value)


def to_rows(records):
    """Flatten StageState records into plain dicts for rendering."""
    rows = []
    for rec in records:
        rows.append({
            "halo": rec["halo"],
            "box": rec["box"],
            "stage": rec["stage"],
            "src": "frozen" if rec.get("frozen") else "registry",
            "state": rec["state"].state,
            "last": _fmt(rec["state"].last),
            "z": _fmt(rec["state"].redshift, "z"),
            "cycle": _fmt(rec["state"].cycle),
            "jobid": _fmt(rec.get("jobid")),
            "note": rec["state"].note or "",
        })
    return rows


def render_text(rows):
    if not rows:
        return "(no stages found)"
    widths = {c: max(len(c.upper()), max(len(r[c]) for r in rows)) for c in COLUMNS}
    out = ["  ".join(c.upper().ljust(widths[c]) for c in COLUMNS).rstrip()]
    out.append("  ".join("-" * widths[c] for c in COLUMNS))
    for r in rows:
        out.append("  ".join(r[c].ljust(widths[c]) for c in COLUMNS).rstrip())
    return "\n".join(out)


def summarize(rows):
    counts = {}
    for r in rows:
        counts[r["state"]] = counts.get(r["state"], 0) + 1
    parts = ["%s %d" % (s, counts[s]) for s in _STATE_ORDER if s in counts]
    for s in sorted(counts):
        if s not in _STATE_ORDER:
            parts.append("%s %d" % (s, counts[s]))
    return "  ".join(parts)


def write_ecsv(rows, path):
    from astropy.table import Table

    if not rows:
        return
    table = Table({c: [r[c] for r in rows] for c in COLUMNS}, names=COLUMNS)
    table.meta["comments"] = [
        "FOGGIE IC pipeline status, generated by ic_pipeline status.",
        "Generated %s" % datetime.datetime.now().isoformat(timespec="seconds"),
    ]
    table.write(path, format="ascii.ecsv", overwrite=True)


_STATE_COLOR = {
    "DONE": "#1f7a52", "RUNNING": "#2f6fb5", "QUEUED": "#6247aa",
    "BUILDING": "#2f6fb5", "READY": "#5c6370", "BLOCKED": "#5c6370",
    "STALLED": "#a8571b",
}


def write_html(rows, path):
    generated = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cells = []
    for r in rows:
        color = _STATE_COLOR.get(r["state"], "#5c6370")
        tds = []
        for c in COLUMNS:
            value = html.escape(r[c])
            if c == "state":
                value = '<b style="color:%s">%s</b>' % (color, value)
            tds.append("<td>%s</td>" % value)
        cells.append("<tr>%s</tr>" % "".join(tds))

    doc = """<!doctype html>
<html><head><meta charset="utf-8"><title>FOGGIE IC pipeline status</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
     margin:40px;color:#16181d;background:#fff}}
h1{{font-size:20px;margin:0 0 4px}}
p.meta{{color:#5c6370;font-size:13px;margin:0 0 20px;font-family:ui-monospace,Menlo,Consolas,monospace}}
table{{border-collapse:collapse;font-size:14px;font-family:ui-monospace,Menlo,Consolas,monospace}}
th,td{{padding:6px 12px;border-bottom:1px solid #d3d7de;text-align:left;white-space:nowrap}}
th{{font-size:11px;letter-spacing:.06em;color:#5c6370;text-transform:uppercase}}
@media (prefers-color-scheme:dark){{
  body{{background:#14161a;color:#e6e8ec}} th,td{{border-bottom-color:#333944}} p.meta{{color:#9aa1ad}}
}}
</style></head><body>
<h1>FOGGIE IC pipeline status</h1>
<p class="meta">generated {generated} &middot; {summary}</p>
<table><thead><tr>{head}</tr></thead><tbody>
{body}
</tbody></table>
</body></html>
""".format(generated=generated,
           summary=html.escape(summarize(rows)),
           head="".join("<th>%s</th>" % c.upper() for c in COLUMNS),
           body="\n".join(cells))

    with open(path, "w") as fp:
        fp.write(doc)
