# Run started Mon Jun  2 14:59:55 2025.
#
# cloudyRunMode = 4 
# outputFilePrefix = TEST_z0_HM12_sh
# outputDir = /Users/vidasaeedzadeh/Documents/02-Projects/02-FOGGIE/Cloudy-runs/outputs/
#
# Commands to be executed everytime:
# failures 200 times map
# iterate to convergence max=2 error=0.20
# CMB redshift 0.00
# Table HM12 redshift 0.00
# set WeakHeatCool -20
# no H2 molecule
# no charge transfer
# metals 0 log
#
# Loop commands and values:
# hden: -6 -5.5 -5 -4.5 -4 -3.5 -3 -2.5 -2 -1.5 -1 -0.5 0 0.5 1 1.5 2
#
#run	hden
1	-6
2	-5.5
3	-5
4	-4.5
5	-4
6	-3.5
7	-3
8	-2.5
9	-2
10	-1.5
11	-1
12	-0.5
13	0
14	0.5
15	1
16	1.5
17	2
