# Run started Wed Jun  3 10:23:46 2026.
#
# cloudyRunMode = 4 
# outputFilePrefix = TEST_z0_HM12_sh
# outputDir = /Users/tumlinson/Dropbox/FOGGIE/foggie/foggie/cgm_emission/How-to-Run-CLOUDY/
#
# Commands to be executed everytime:
# failures 200 times map
# iterate to convergence max=2 error=0.20
# CMB redshift 0.00
# Table HM12 redshift 0.00
# set WeakHeatCool -20
# no H2 molecule
# no charge transfer
# metals 0 log
#
# Loop commands and values:
# hden: -6 -5.5 -5
#
#run	hden
1	-6
2	-5.5
3	-5
